import { useMediaQuery } from "@react-hook/media-query";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.sass";
import { Plan } from "../components/Plan";
import blueBokeh from "../public/assets/blue-bokeh.png";
import lightsBokeh from "../public/assets/lights-bokeh.png";
import { PLANS, PLANS_REV } from "../constants";

export default function Home() {
  const match = useMediaQuery("only screen and (max-width: 600px)");

  return (
    <div className={styles.container}>
      <Head>
        <title>Popflick</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.behindContainer}>
          <div className={styles.blueBokeh}>
            <Image src={blueBokeh} alt="Blue Bokeh" />
          </div>
          <div className={styles.lightsBokeh}>
            <Image src={lightsBokeh} alt="Lights Bokeh" />
          </div>
        </div>
        <div className={styles.container}>
          <h1 className={styles.title}>Choose your Plan. Always Ad-free.</h1>
          <h3 className={styles.subtitle}>Cancel anytime.</h3>
          <div className={styles.plans}>
            <h2 className={styles.plans_title}>Step 2 of 2</h2>
            <h4 className={styles.plans_helptext}>
              Already have an account? <strong>Login</strong>
            </h4>
            <div>
              {match
                ? PLANS_REV.map((plan, index) => (
                    <Plan key={index} plan={plan} />
                  ))
                : PLANS.map((plan, index) => <Plan key={index} plan={plan} />)}
            </div>
          </div>
          <h2 className={styles.subscribe_text}>
            Subscribe now to watch Popflick Ad-free.
          </h2>
          <p className={styles.subscribe_reason}>
            Keep an eye on our ever-expanding collection of movies, TV shows and
            all sorts of interesting video content. Meet great characters,
            explore new worlds & enjoy the Popflick experience.
          </p>
        </div>
      </main>
    </div>
  );
}
